name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: poetry install
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        $HOME/.poetry/bin/poetry install
    - name: black
      run: |
        $HOME/.poetry/bin/poetry run black --check --line-length 120 .
    - name: pytest
      run: |
        $HOME/.poetry/bin/poetry run pytest tests
